// Copyright © 2026 Manolo Remiddi · SPDX-License-Identifier: MIT
import test from 'node:test';import assert from 'node:assert/strict';
import {presets,validate,serialize,documentFor,filename} from '../assets/skin-format.mjs';
import {readFileSync} from 'node:fs';
test('downloadable built-ins exactly match editor exports',()=>{for(const [name,value] of Object.entries(presets)){const file='assets/skins/'+name.toLowerCase().replaceAll(' ','-')+'.augmentor-skin.json';assert.deepEqual(JSON.parse(readFileSync(file)),documentFor(name,value));}});
test('custom colours and every appearance option survive export',()=>{const appearance={...presets.Futuristic,theme:'light',hue:359,brightness:-15,accent_hue:0,accent_brightness:15,saturation:100,opacity:35,animation:false,flares:false,effect:'butterflies',format_colours:{heading:'#123abc',comment:'#998877'}};assert.deepEqual(JSON.parse(serialize('  My skin  ',appearance)).appearance,appearance);assert.equal(JSON.parse(serialize('  My skin  ',appearance)).name,'My skin');});
test('rejects malformed types, commands, unrelated settings and colours',()=>{for(const changes of [{opacity:true},{hue:360},{effect:'execute'},{theme:'automatic'},{background_image:'stray data'},{format_colours:{unknown:'#123456'}},{format_colours:{heading:'url(https://example.com)'}},{token:'private'}])assert.throws(()=>documentFor('Bad',{...presets.Futuristic,...changes}));for(const name of ['','\nBad','x'.repeat(81)])assert.throws(()=>documentFor(name,presets.Futuristic));assert.throws(()=>validate({...documentFor('Good',presets.Futuristic),extra:1}));});
test('legacy skins default absent background fields; version 2 is required for image export',()=>{const doc=documentFor('Legacy',presets.Futuristic);delete doc.appearance.background;delete doc.appearance.background_image;assert.equal(validate(doc).appearance.background,'none');const image={...presets.Futuristic,background:'uploaded',background_image:'YWJj'};assert.equal(documentFor('Image',image).version,2);assert.throws(()=>validate({...documentFor('Image',image),version:1}));assert.throws(()=>documentFor('Image',{...image,background_image:'<svg>'}));});
test('filenames cannot inject paths; skin data contains no other preferences',()=>{assert.equal(filename('../../'), 'my-skin.augmentor-skin.json');const doc=documentFor('Named',presets.Futuristic);assert.deepEqual(Object.keys(doc).sort(),['appearance','format','name','version']);});
